name: Comment on pull request

on:
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: deborah-digges/new-pull-request-comment-action@v1.9
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}

